# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
import numpy as np
arr=np.arange(0,10)
arr2=arr.reshape(2,5)
print("1D array =",arr)
print("2D Array\n",arr2)

1D array = [0 1 2 3 4 5 6 7 8 9]
2D Array
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [14]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.ones(10).reshape(2,5).astype(np.int)
arr3=np.vstack((arr1,arr2))
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.ones(10).reshape(2,5).astype(np.int)
arr3=np.hstack((arr1,arr2))
print(arr3)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [28]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(arr,"\n============================")
print(arr.ravel())

[[0 1 2 3 4]
 [5 6 7 8 9]] 
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [29]:
arr=np.arange(0,15).reshape(5,3)
print(arr,"\n=======================")
print(arr.flatten())

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [30]:
arr=np.arange(0,15)
print(arr,"\n=======================")
print(arr.reshape(5,3))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


## Question:7

### Create 5x5 an array and find the square of an array?

In [36]:
arr=np.random.randn(5,5)
print("Array\n",arr,"\n==========================================================")
print("Square of Array\n",np.square(arr))

Array
 [[ 0.90994516  0.64421731 -0.26382248  1.21892154 -0.0793505 ]
 [-2.46939523 -0.31725403 -0.17975276  0.53936596 -0.72046971]
 [-0.85005576  0.42484343  0.85675334  0.11424524  1.43940568]
 [-0.68792314 -0.46282724 -0.04948047 -0.28403695 -0.89881144]
 [-1.17425109 -0.24216862 -0.48777649 -0.00641339 -1.0050052 ]] 
Square of Array
 [[8.28000200e-01 4.15015944e-01 6.96023013e-02 1.48576971e+00
  6.29650168e-03]
 [6.09791279e+00 1.00650120e-01 3.23110537e-02 2.90915638e-01
  5.19076598e-01]
 [7.22594802e-01 1.80491938e-01 7.34026290e-01 1.30519752e-02
  2.07188871e+00]
 [4.73238245e-01 2.14209057e-01 2.44831655e-03 8.06769911e-02
  8.07862007e-01]
 [1.37886562e+00 5.86456418e-02 2.37925902e-01 4.11315737e-05
  1.01003545e+00]]


## Question:8

### Create 5x6 an array and find the mean?

In [39]:
arr=np.random.randint(10,100,30).reshape(5,6)
print("Array\n",arr,"\n==========================")
print("Mean of Array = ",np.mean(arr))

Array
 [[65 98 29 21 10 32]
 [89 61 66 68 73 42]
 [52 71 67 18 85 87]
 [88 65 83 24 30 75]
 [90 42 70 25 50 54]] 
Mean of Array =  57.666666666666664


## Question:9

### Find the standard deviation of the previous array in Q8?

In [40]:
print("Standard daviation of array = ",np.std(arr))

Standard daviation of array =  24.699977507862002


## Question:10

### Find the median of the previous array in Q8?

In [41]:
print("Median of array = ",np.median(arr))

Median of array =  65.0


## Question:11

### Find the transpose of the previous array in Q8?

In [44]:
print("Array\n",arr,"\n=====================")
print("Transpose of array\n",np.transpose(arr))

Array
 [[65 98 29 21 10 32]
 [89 61 66 68 73 42]
 [52 71 67 18 85 87]
 [88 65 83 24 30 75]
 [90 42 70 25 50 54]] 
Transpose of array
 [[65 89 52 88 90]
 [98 61 71 65 42]
 [29 66 67 83 70]
 [21 68 18 24 25]
 [10 73 85 30 50]
 [32 42 87 75 54]]


## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [61]:
arr=np.random.randint(1,20,16).reshape(4,4)
print("Array\n",arr,"\n=================")
print("Sum of diagonal elements(Trace) = ",np.trace(arr))

Array
 [[18 16 15  9]
 [19  9  2 10]
 [ 1 15  4 14]
 [ 2 18 18 15]] 
Sum of diagonal elements(Trace) =  46


## Question:13

### Find the determinant of the previous array in Q12?

In [65]:
from numpy.linalg import det
print("Determinant of the Array is = ",det(arr))

Determinant of the Array is =  21287.99999999999


## Question:14

### Find the 5th and 95th percentile of an array?

In [68]:
print("Array\n",arr,"\n=================")
print("5th percentile of array is = ",np.percentile(arr,5))
print("95th percentile of array is = ",np.percentile(arr,95))

Array
 [[18 16 15  9]
 [19  9  2 10]
 [ 1 15  4 14]
 [ 2 18 18 15]] 
5th percentile of array is =  1.75
95th percentile of array is =  18.25


## Question:15

### How to find if a given array has any null values?

In [75]:
a=np.array([1,22,0,13,5])
(a==0).any()

True