# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
nv=np.zeros(10)
print(nv)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [6]:
vc=np.arange(10,50)
print(vc)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [7]:
print(vc.shape)

(40,)


5. Print the type of the previous array in question 3

In [8]:
print(vc.dtype)

int32


6. Print the numpy version and the configuration


In [75]:
print("numpy version = ",np.__version__)
print(np.show_config())

numpy version =  1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Syed/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Syed/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\

7. Print the dimension of the array in question 3


In [9]:
print(vc.ndim)

1


8. Create a boolean array with all the True values

In [11]:
bar=np.array([1,2,3,4,5])
bar=bar>0
print(bar)

[ True  True  True  True  True]


9. Create a two dimensional array




In [12]:
twoD=np.arange(4).reshape(2,2)
print(twoD)

[[0 1]
 [2 3]]


10. Create a three dimensional array



In [13]:
threeD=np.arange(18).reshape(2,3,3)
print(threeD)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [14]:
a=np.arange(10)
print(a)
print('=====================')
print(a[-1::-1])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [15]:
nullVector=np.zeros(10)
nullVector[4]=1
print(nullVector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [16]:
idm=np.identity(3)
print(idm)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [60]:
arr=np.array([1,2,3,4,5])
arr=arr.astype(np.float)
print(arr)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [61]:
arr1=np.array([[1.,2.,3.],[4.,5.,6.]])
arr2=np.array([[0.,4.,1.],[7.,2.,12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [15]:
c1=np.maximum(arr1,arr2)
c2=np.minimum(arr1,arr2)
print("comparing by maximum values for respective indexes \n {0} \n comparing by minimum vlaue for respetive indexes \n {1}".format(c1,c2))

comparing by maximum values for respective indexes 
 [[ 1.  4.  3.]
 [ 7.  5. 12.]] 
 comparing by minimum vlaue for respetive indexes 
 [[0. 2. 1.]
 [4. 2. 6.]]


17. Extract all odd numbers from arr with values(0-9)

In [16]:
arr=np.arange(0,10)
print(arr,"\n=====================")
arr_odd=arr[arr%2!=0]
print(arr_odd)

[0 1 2 3 4 5 6 7 8 9] 
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [62]:
arr[arr%2!=0]=-1
print(arr)

[-1.  2. -1.  4. -1.]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [63]:
arr=np.arange(10)
arr[5:9]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [64]:
arr=np.ones(25).reshape(5,5)
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [65]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]=12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [66]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [22]:
arr2d=np.arange(0,10).reshape(2,5)
print(arr2d,"\n================")

print(arr2d[0:1,0:])

[[0 1 2 3 4]
 [5 6 7 8 9]] 
[[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [23]:
arr2d=np.arange(0,10).reshape(2,5)
print(arr2d,"\n================")

print(arr2d[1:,0:])

[[0 1 2 3 4]
 [5 6 7 8 9]] 
[[5 6 7 8 9]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [24]:
arr2d=np.arange(0,10).reshape(2,5)
print(arr2d,"\n================")

print(arr2d[0:,2:3])

[[0 1 2 3 4]
 [5 6 7 8 9]] 
[[2]
 [7]]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
arr=np.random.randn(10,10)
max=np.argmax(arr)
min=np.argmin(arr)
print("maximum value is  {0} \nminimum value is {1}".format(max,min))

maximum value is  24 
minimum value is 97


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [67]:
a=np.array([1,2,3,2,3,4,3,4,5,6]) 
b= np.array([7,2,10,2,7,4,9,4,9,8])
print(a[a==b])

[2 2 4 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [68]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.where(a==b)
print(c)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Atual Data\n",data,"\n===============================================")
print("Required Data\n",data[names!='Will'])

Atual Data
 [[ 1.19774549  2.58645766 -0.52644847 -0.14207226]
 [ 1.05422009 -0.61122373 -1.44152445  0.69697365]
 [-0.92191584 -0.19190057  1.00287843 -1.46231911]
 [-0.7962617  -1.63708146  0.11020728 -1.35816441]
 [ 0.18741424 -1.5481929  -1.25609646 -1.12557166]
 [-1.00093013 -1.63441643  0.11397082  0.34543297]
 [-1.65490589  0.24162209  0.52141577  0.39923265]] 
Required Data
 [[ 1.19774549  2.58645766 -0.52644847 -0.14207226]
 [ 1.05422009 -0.61122373 -1.44152445  0.69697365]
 [-0.7962617  -1.63708146  0.11020728 -1.35816441]
 [-1.00093013 -1.63441643  0.11397082  0.34543297]
 [-1.65490589  0.24162209  0.52141577  0.39923265]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [38]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Atual Data\n",data,"\n===============================================")
print("Required Data\n",data[(names!='Will')&(names!='Joe')])

Atual Data
 [[ 1.73913265 -1.99825377 -0.46661712 -1.312076  ]
 [-0.93412686 -0.6570274  -0.63347229 -0.94011801]
 [ 0.69648224  0.91224866 -1.00920404 -0.29152982]
 [ 0.54391408 -1.14419173 -0.8016618   1.61350099]
 [-0.05241    -0.40168191  0.32765003 -0.31519824]
 [-0.51575401  0.16272157 -1.02525714 -0.48529268]
 [-1.82644338 -0.81812538 -1.58679111  1.30833596]] 
Required Data
 [[ 1.73913265 -1.99825377 -0.46661712 -1.312076  ]
 [ 0.54391408 -1.14419173 -0.8016618   1.61350099]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [53]:
arr2d=np.arange(1,16).reshape(5,3)
arrDecimal=arr2d.astype(np.float)
print("Decimal Array\n",arrDecimal)

Decimal Array
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [64]:
arr2d=np.arange(1,17).reshape(2,2,4)
arrDecimal=arr2d.astype(np.float)
print("Decimal Array of 3d shape\n",arrDecimal)

Decimal Array of 3d shape
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [87]:
print("swaping array\n",np.swapaxes(arrDecimal,1,2))

swaping array
 [[[ 1.  5.]
  [ 2.  6.]
  [ 3.  7.]
  [ 4.  8.]]

 [[ 9. 13.]
  [10. 14.]
  [11. 15.]
  [12. 16.]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [2]:
arr=np.random.randn(10)
arr=np.abs(arr)
print("Actual Array\n",arr,"\n====================================")
arrS=np.sqrt(arr)
print("After Squar root\n",arrS,"\n===================================")
ans=arrS
ans[ans<0.5]=0
print("The required array\n",ans)


Actual Array
 [2.36074835 0.73652941 0.85675541 0.68655438 0.35083629 0.48729913
 0.10330319 1.24979875 1.08815826 0.09055583] 
After Squar root
 [1.5364727  0.85821292 0.92561083 0.82858577 0.59231435 0.69806814
 0.32140814 1.11794398 1.04314825 0.30092496] 
The required array
 [1.5364727  0.85821292 0.92561083 0.82858577 0.59231435 0.69806814
 0.         1.11794398 1.04314825 0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [18]:
arr1=np.random.randn(12)*10
arr2=np.random.randn(12)*10
print("Array 1\n",arr1,"\n==================")
print("Array 2\n",arr2,"\n==================")
x=np.maximum(arr1,arr2)
print("Required Array\n",x)


Array 1
 [ 13.59311669  15.61530247   9.40941836 -24.00545887   0.3270734
 -19.44966711  25.32537903  -3.58561085 -15.73656677  -3.60701917
  -0.98398488  -9.51420662] 
Array 2
 [  3.69526675   3.05775932 -10.11291816  13.88850685  -3.42975231
 -16.91263606  -6.90594839  10.49162143  -4.12178039  -7.33151484
  -1.500754     1.73056376] 
Required Array
 [ 13.59311669  15.61530247   9.40941836  13.88850685   0.3270734
 -16.91263606  25.32537903  10.49162143  -4.12178039  -3.60701917
  -0.98398488   1.73056376]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x=np.unique(names)
print(np.sort(x))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [70]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print(np.delete(b,a-1))

[]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [71]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[:,1:2]=newColumn.T
print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [41]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("x =\n",x)
print("y =\n",y)
z=x@y
print("x.y(dot product) =\n",z)

x =
 [[1. 2. 3.]
 [4. 5. 6.]]
y =
 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
x.y(dot product) =
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [72]:
x=np.random.randint(1,100,20).reshape(5,4)
print("matrix is\n",x)
y=np.cumsum(x)
print("cumsum of matrix is\n",y)

matrix is
 [[36 94 86 54]
 [17  5  8 14]
 [99 22  2  3]
 [26 82 22  6]
 [70 24 69 33]]
cumsum of matrix is
 [ 36 130 216 270 287 292 300 314 413 435 437 440 466 548 570 576 646 670
 739 772]
